version: '3.8'

services:
  app:
    container_name: onibusgo
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3333:3333"
    command: npm run start
    environment:
      - NODE_ENV=production