import { MigrationInterface, QueryRunner } from "typeorm";

export class Default1741355627841 implements MigrationInterface {
    name = 'Default1741355627841'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "VIDEOS" ("ID" number GENERATED BY DEFAULT AS IDENTITY, "UUID" varchar2(255) NOT NULL, "TITLE" varchar2(255) NOT NULL, "DESCRIPTION" varchar2(255) NOT NULL, CONSTRAINT "UNIQUE_UUID_AND_TITLE" UNIQUE ("UUID", "TITLE"), CONSTRAINT "PK_e76d93352c6ffecf8cf0d3607d2" PRIMARY KEY ("ID"))`);
        await queryRunner.query(`CREATE TABLE "CHUNKS" ("ID" number GENERATED BY DEFAULT AS IDENTITY, "UUID" varchar2(255) NOT NULL, "LANGUAGE" varchar2(255) NOT NULL, "TIMESTAMP" varchar2(255) NOT NULL, "TEXT" varchar2(255) NOT NULL, CONSTRAINT "PK_da71cfd8cae545253d3784a4e43" PRIMARY KEY ("ID"))`);
        await queryRunner.query(`CREATE TABLE "USUARIOS" ("UUID" number GENERATED BY DEFAULT AS IDENTITY, "USERNAME" varchar2(255) NOT NULL, "PASSWORD" varchar2(255) NOT NULL, CONSTRAINT "PK_0d863bf429e491a2f11ba3d51f6" PRIMARY KEY ("UUID"))`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP TABLE "USUARIOS"`);
        await queryRunner.query(`DROP TABLE "CHUNKS"`);
        await queryRunner.query(`DROP TABLE "VIDEOS"`);
    }

}
