import { MigrationInterface, QueryRunner } from "typeorm";

export class Default1741292306708 implements MigrationInterface {
    name = 'Default1741292306708'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "VIDEOS" ("ID" number GENERATED BY DEFAULT AS IDENTITY, "UUID" varchar2(255) NOT NULL, "TITLE" varchar2(255) NOT NULL, "DESCRIPTION" varchar2(255) NOT NULL, CONSTRAINT "PK_e76d93352c6ffecf8cf0d3607d2" PRIMARY KEY ("ID"))`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP TABLE "VIDEOS"`);
    }

}
