import { MigrationInterface, QueryRunner } from "typeorm";

export class Default1741029953227 implements MigrationInterface {
    name = 'Default1741029953227'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "CHUNKS" ("UUID" number GENERATED BY DEFAULT AS IDENTITY, "VIDEOID" varchar2(255) NOT NULL, "TIMESTAMP" varchar2(255) NOT NULL, "TEXT" varchar2(255) NOT NULL, CONSTRAINT "PK_21dd4c6262aaadfbd68abdf078a" PRIMARY KEY ("UUID"))`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP TABLE "CHUNKS"`);
    }

}
